### ISSUE TITLE
Try to catch case of Spotify client not running

### ISSUE THREAD

**Issue by barsnick** [fr31/spotifylyrics#53]
This applies to Linux - I have no idea what happens on Windows:

When I don't have Spotify running, or close it while spotifylyrics is running, the DBUS code will throw an exception, probably because the query for the spotify-client fails:

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "SpotifyLyrics.pyw", line 279, in lyrics_thread
    songname = backend.getwindowtitle()
  File "/home/barsnick/Development/spotifylyrics/backend.py", line 104, in getwindowtitle
    metadata = spotifyinterface.Get("org.mpris.MediaPlayer2.Player", "Metadata")
  File "/usr/lib64/python3.5/site-packages/dbus/proxies.py", line 70, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib64/python3.5/site-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib64/python3.5/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
```
SpotifyLyrics doesn't catch up once I run spotify-client (while leaving SpotifyLyrics running).

In another run, I got this, which is different:
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/python3.5/site-packages/dbus/bus.py", line 175, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/usr/lib64/python3.5/site-packages/dbus/bus.py", line 361, in get_name_owner
    's', (bus_name,), **keywords)
  File "/usr/lib64/python3.5/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'org.mpris.MediaPlayer2.spotify': no such name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "SpotifyLyrics.pyw", line 279, in lyrics_thread
    songname = backend.getwindowtitle()
  File "/home/barsnick/Development/spotifylyrics/backend.py", line 102, in getwindowtitle
    spotifydbus = session.get_object("org.mpris.MediaPlayer2.spotify", "/org/mpris/MediaPlayer2")
  File "/usr/lib64/python3.5/site-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib64/python3.5/site-packages/dbus/proxies.py", line 248, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib64/python3.5/site-packages/dbus/bus.py", line 180, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib64/python3.5/site-packages/dbus/bus.py", line 278, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/lib64/python3.5/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name org.mpris.MediaPlayer2.spotify was not provided by any .service files
```
This is pretty obvious, the query for spotify failed. I don't know whether SpotifyLyrics runs fine nevertheless.

Perhaps these exceptions are worth taking a look and handling.

Thanks for a tool which I really dig!

**Comment by fr31** [comment]
This is fixed.
