### ISSUE TITLE
It is impossible to download the requirements automatically

### ISSUE THREAD

**Issue by boreq** [fr31/spotifylyrics#57]
```
(venv) [user@host spotifylyrics]$ pip install -r requirements.txt 
Collecting beautifulsoup4==4.5.1 (from -r requirements.txt (line 1))
  Downloading beautifulsoup4-4.5.1-py3-none-any.whl (83kB)
    100% |████████████████████████████████| 92kB 1.3MB/s 
Collecting pypiwin32==219 (from -r requirements.txt (line 2))
  Downloading pypiwin32-219.zip (4.8MB)
    100% |████████████████████████████████| 4.8MB 257kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-n0s70mch/pypiwin32/setup.py", line 121
        print "Building pywin32", pywin32_version
                               ^
    SyntaxError: Missing parentheses in call to 'print'
    
    ----------------------------------------
(venv) [user@host spotifylyrics]$ python --version
Python 3.6.1
(venv) [user@host spotifylyrics]$ pip --version
pip 9.0.1 from /home/user/spotifylyrics/venv/lib/python3.6/site-packages (python 3.6)
```

**Comment by HF0** [comment]
This is because you are using python 3.6 (README says you should be using 3.5)
If you want to keep using 3.6 you have to change pypiwin32==219 to pypiwin32==220 in requirements.txt

**Comment by fr31** [comment]
It should be possible now with the latest version.
